### PR TITLE
Added header , light & dark mode functionality ,edited footer  + changed some colors

### PR DESCRIPTION
**Pull request by mallickboy**

### CODE REVIEW

**Comment by pruthvirajjadhav1** [comment]
The main purpose of this website is to keep the features at a minimum and I don't think we need a dark mode option here.

**Comment by pruthvirajjadhav1** [comment]
You could keep the BG color default and try putting our mascot in the header that could work or maybe arrange the mascot in the right position

**Comment by mallickboy** [comment]
done

**Comment by mallickboy** [comment]
Default bg color + mascot in header

**Comment by pruthvirajjadhav1** [comment]
It has some merge conflicts try `git pull` the push

**Comment by mallickboy** [comment]
done + added title bar icon

**Comment by pruthvirajjadhav1** [comment]
Looks good👍
Do ⭐ this Repo

Looking forward for more contributions🙌

QualityGIF

**Comment by mallickboy** [comment]
> Looks good+1 Do star this Repo
> 
> Looking forward for more contributionsraised_hands
> 
> QualityGIF [ QualityGIF ](https://user-images.githubusercontent.com/73253354/198957038-83302b09-1ac4-4828-aba2-fda4f0b11bcc.gif) [ ](https://user-images.githubusercontent.com/73253354/198957038-83302b09-1ac4-4828-aba2-fda4f0b11bcc.gif)
done

**Comment by mallickboy** [comment]
thank you & ofcourse

**Pull request merged**
