### PR TITLE
made aesthetic changes

### PR DESCRIPTION
**Pull request by S-HARI-S**
added padding to image and made it responsive and changed the size of time and cw

### CODE REVIEW

**Comment by pruthvirajjadhav1** [comment]
Screenshot (87)

Its UI kinda got messed up I gave that image size because when a user comes on this site he should see the typing board at first. Trying adjusting the image

**Comment by pruthvirajjadhav1** [comment]
Screenshot (88)

It should look like this when a user comes everything should be visible

**Comment by S-HARI-S** [comment]
ok...I'll fix that up

**Comment by S-HARI-S** [comment]
I restored the width and corrected the alignment of image and text , and added a margin .

**Comment by pruthvirajjadhav1** [comment]
I will close this PR cause If I merge this PR it will go to spam and try improving the UI and then PR.
KeepUpTheGoodWorkKeepItUpGIF

**Pull request closed without merging**
